image: docker-ungp.softplan.com.br/docker-jvm-maven-jdk-11-gcloud:1.0.0-RC4

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -T4"
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -DdependencyLocationsEnabled=false -Dmaven.repo.local=.m2/repository -Xms256m -Xmx4g -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=1g"
  POM_PATH: "./pom.xml"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository/

stages:
  - compile
  - deploy
  - promote
  - tag

promote-version:
  stage: promote
  services:
    - docker:dind
  before_script:
    - git config --global user.email "$GIT_USER@softplan.com.br"
    - git config --global user.name "$GIT_USER"
    - git remote set-url origin https://"$GIT_USER:$GIT_PASS"@gitlab.ungp.softplan.com.br/$CI_PROJECT_PATH.git
  script:
    - mvn $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.4:set -DnewVersion=${version}
    - mvn $MAVEN_CLI_OPTS package
    - git add .
    - git commit -m "Changed version to ${version}"
    - git push origin HEAD:$CI_COMMIT_REF_SLUG
    - git tag -a ${version} -m "Version created by gitlab-ci Build ${version}"
    - git push origin ${version}
  only:
    refs:
      - web
    variables:
      - $stage == "promote"
  except:
    variables:
      - $stage == "deploy"

deploy-gcloud:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - git config --global user.email "$GIT_USER@softplan.com.br"
    - git config --global user.name "$GIT_USER"
    - git remote set-url origin https://"$GIT_USER:$GIT_PASS"@gitlab.ungp.softplan.com.br/$CI_PROJECT_PATH.git
  script:
    - gcloud config set project ${projectId}
    - make deploy version=${version} projectId=${projectId}
    - git add .
    - git commit -m "Changed version to ${version}"
    - git push origin HEAD:$CI_COMMIT_REF_SLUG
    - git tag -a ${version} -m "Version created by gitlab-ci Build ${version}"
    - git push origin ${version}
  only:
    refs:
      - web
    variables:
      - $stage == "deploy"
  except:
    variables:
      - $stage == "promote"

compile-test:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS package
  except:
    - tags
    - web
